library(shiny)
library(shinydashboard) 
library(htmltools)
library(ggplot2)
library(tidyverse)
library(DT)


# download file and extract data
temp <- tempfile()
download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/00275/Bike-Sharing-Dataset.zip",temp)
dat.1 <- read.csv(unz(temp, "day.csv"), stringsAsFactors = F)
unlink(temp)

# copy data
dt.1 <- (dat.1)

# group variables
col.grp <- colnames(dt.1)[3:9]
for(i in c(3:9)){
  dt.1[,i] <- as.factor(dt.1[,i])
}

# ggplot(dt.1, aes(x = season, y = casual)) + geom_boxplot()
# continuous variables
col.num <- colnames(dt.1)[10:13]
# destiny variables
col.dest <- colnames(dt.1)[14:16]

##### 
# ui
ui <- dashboardPage(skin = "green",
                    dashboardHeader(title = "Bike Sharing"),
                    ### side bar
                    dashboardSidebar(
                      sidebarMenu(
                      # menu introdunction
                      menuItem("Introduction", tabName = "intro", icon = icon("globe", lib = "font-awesome")),
                      # menu variable correlation
                      menuItem("Variable correlation", tabName = "V_cor", icon = icon("binoculars", lib = "font-awesome")),
                      # menu linear regression
                      menuItem("Linear Regressoin", tabName = "L_R", icon = icon("chart-line", lib = "font-awesome")),
                      # menu data view
                      menuItem("Data View", tabName = "dt_view", icon = icon("fire", lib = "font-awesome"))
                    )),
                    ### body
                    dashboardBody(
                      # tabItems
                      tabItems(
                        # subitem: introdunction
                        tabItem(tabName =  "intro",tags$body(HTML(
                          "<p><h1>Bike Sharing Dataset</h1>
                                <h3>Author:Jingcheng Xu</h3>
                                <h3>Data Set Information:</h3>
                                Bike sharing systems are new generation of traditional bike rentals where 
                                whole process from membership, rental and return back has become automatic. 
                                Through these systems, user is able to easily rent a bike from a particular 
                                position and return back at another position. Currently, there are about over 
                                500 bike-sharing programs around the world which is composed of over 500 
                                thousands bicycles. Today, there exists great interest in these systems due to 
                                their important role in traffic, environmental and health issues.</br>
                                Apart from interesting real world applications of bike sharing systems, 
                                the characteristics of data being generated by these systems make them attractive 
                                for the research. Opposed to other transport services such as bus or subway, 
                                the duration of travel, departure and arrival position is explicitly recorded 
                                in these systems. This feature turns bike sharing system into a virtual sensor 
                                network that can be used for sensing mobility in the city. Hence, it is expected 
                                that most of important events in the city could be detected via monitoring these data.
                                </br></br>
                                <h3>Pros and Cons of Bike Sharing:</h3>
                                <h4>Pros of Bike Shares:</h4>
                                1. Convenience </br>
                                2. Environment and Tourism Benefits  </br>
                                3. Healthier Nation </br> 
                                4. Cycling Laws Improvement </br>
                                5. Safer and More Bike Lanes </br>
                                <h4>Cons of Bike Shares:</h4> 
                                1. Congested Bike Docks </br>
                                2. First-Time Bikers </br>
                                3. Biking without helmet </br>
                                </br></br>
                                </p>")),
                          tags$div(tags$p("Data Source:"),
                                   tags$a(href="https://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset", 
                                          "https://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset")),
                          
                          textOutput("intro")
                      
                    ),
                    # subitem data view
                    tabItem(tabName =  "dt_view",
                            fluidRow(
                              DT::dataTableOutput("mytable1")
                              )
                    ),
                    # subitem Variable correlation
                    tabItem(tabName =  "V_cor",
                            fluidRow(
                              box(title = "Variables Relations", solidHeader = TRUE,width = 8,status = "primary",
                                  plotOutput("plot_relations")
                                  # test
                                  # verbatimTextOutput("test2")
                                ),
                              
                              # box for x & y-lab
                              box(title = "Select Varibles", solidHeader = TRUE,width = 3,status = "warning",
                                  selectInput(inputId = "cor_x", label = strong("Select X lab"),
                                              choices = c(col.grp,col.num),
                                              selected = col.grp[1]),
                                  selectInput(inputId = "cor_y", label = strong("Select Y lab"),
                                              choices = col.dest,
                                              selected = col.dest[1]) 
                              )
                              
                            )
                    ),
                    # subitem 
                    tabItem(tabName =  "L_R",
                            fluidRow(
                              box(title = "Linear Regression", solidHeader = TRUE,width = 8,status = "primary",
                                  verbatimTextOutput("LM_form_output"),
                                  # linear regression output
                                  verbatimTextOutput("LM_output")
                              ),
                              box(title = "Select Varibles", solidHeader = TRUE,width = 3,status = "warning",
                                  selectInput(inputId = "reg_x", label = "Independent Variables", 
                                          multiple = TRUE, choices = as.list(c(col.grp,col.num)), 
                                          selected = c(col.grp,col.num)),
                                  br(),
                                  selectInput(inputId = "reg_y", label = strong("Target Variable"),
                                              choices = col.dest,
                                              selected = col.dest[1])
                              )
                            )
                    )
                    
                    ) # end of tabItems
                    
                    )
)

#####
# server
server <- function(input, output){
  
  # subitem data view
  output$mytable1 <- DT::renderDataTable({
    DT::datatable(dt.1)
  })
  
  # plot_relations
  output$plot_relations <- renderPlot({
    if(input$cor_x %in% col.grp){
      # ggplot(dt.1, aes(x = input$cor_x, y = input$cor_y)) + geom_boxplot()
      boxplot(dt.1[, input$cor_y] ~ dt.1[, input$cor_x], xlab = input$cor_x, ylab = input$cor_y, main = "Correlations")
    }else{
      plot(dt.1[, input$cor_x], dt.1[, input$cor_y], xlab = input$cor_x, ylab = input$cor_y, main = "Correlations")
    }

  })
  
  # for test use
  # output$test2 <- renderPrint({
  #   c(input$cor_x, input$cor_y)
  # })
  
  
  # LM_form_output
  output$LM_form_output <- renderPrint({
    form1 <- as.formula(paste(input$reg_y, "~", paste(input$reg_x,  collapse = " + ")))
    form1
  })
  
  # LM_output
  output$LM_output <- renderPrint({
    
    form1 <- as.formula(paste(input$reg_y, "~", paste(input$reg_x,  collapse = " + ")))
    lm.1 <- lm(form1, data = dt.1)
    summary(lm.1)
    
  })
}

# Run the application 
shinyApp(ui = ui, server = server)






